Revert "MapR [SPARK-705] Spark streaming fail with NoSuchMethodError: org.apache.kafka.clients.producer.ProducerConfig.getBoolean(Ljava/lang/String;)Ljava/lang/Boolean; (#645)" (#646)
This reverts commit 82592537599f753932349be5068f81601cc7f433.