MapR [SPARK-972] STS start fail due to java.lang.NoSuchMethodError: 'org.apache.curator.framework.api.ProtectACLCreateModePathAndBytesable org.apache.curator.framework.api.CreateBuilder.creatingParentsIfNeeded()' (#916)